name: Changeset Release
on:
  pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm run test
      - run: echo ${{ github.event.pull_request }}