name: deploy
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
env:
  CI: true
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - name: install dependencies
        run: pnpm install
      - name: run test script
        run: pnpm test:unit
      - name: build
        run: pnpm build
      - name: setup pages
        uses: actions/configure-pages@v4
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
