name: publish
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
env:
  CI: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - name: install dependencies
        run: pnpm install
      - name: run test script
        run: pnpm test:unit
      - name: publish to npm
        run: pnpm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
