name: pull request
on:
  pull_request:
    branches:
      - main
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - name: install dependencies
        run: pnpm install
      - name: run test script
        run: pnpm test:unit
